name: Windows

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    name: "build: ${{ matrix.arch }} ${{ matrix.config }} ${{ matrix.link }}"
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        config: [Release]
        link: [dll]

        include:
        - link: static
          shlib: "OFF"
        - link: dll
          shlib: "ON"
    steps:
      - uses: actions/checkout@v3
      - name: configure
        run: cmake -Bbuild -DUSE_ASYNC:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shlib }} -A ${{ matrix.arch }} -DUSE_MBROLA:BOOL=OFF -DUSE_LIBSONIC:BOOL=OFF -DUSE_LIBPCAUDIO:BOOL=OFF -DUSE_KLATT:BOOL=OFF -DUSE_SPEECHPLAYER:BOOL=OFF -DEXTRA_cmn:BOOL=ON -DEXTRA_ru:BOOL=ON
      - name: make
        run: cmake --build build --config ${{ matrix.config }}
      - name: make check
        run: ctest --test-dir build -Ttest -C ${{ matrix.config }} -j1 --output-on-failure
