name: Windows

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    name: "build: ${{ matrix.arch }} ${{ matrix.config }} ${{ matrix.link }}"
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
    steps:
      - uses: actions/checkout@v3
      - name: configure
        run: |
          cmake -Bbuild \
            -DCMAKE_INSTALL_PREFIX=_install/espeak-ng \
            -DUSE_ASYNC:BOOL=OFF \
            -DBUILD_SHARED_LIBS:BOOL=ON \
            -DUSE_MBROLA:BOOL=OFF \
            -DUSE_LIBSONIC:BOOL=OFF \
            -DUSE_LIBPCAUDIO:BOOL=OFF \
            -DUSE_KLATT:BOOL=OFF \
            -DUSE_SPEECHPLAYER:BOOL=OFF \
            -DEXTRA_cmn:BOOL=ON \
            -DEXTRA_ru:BOOL=ON
      - name: build
        run: |
          cmake --build build --config Release
      - name: install
        run: |
          cmake --install build
      - name: package
        run: |
          cd _install
          Compress-Archive -LiteralPath espeak-ng -DestinationPath espeak-ng_Windows_${{ matrix.arch }}.zip
